config/routes.rb
Rails.application.routes.draw do
  
  resources :projects
  devise_for :users

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :description, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :is_private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
= link_to t('.create project', :default => t("helpers.links.new_project")), new_project_path, class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
          %title= content_for?(:title) ? yield(:title) : "InvoToDo"
          = csrf_meta_tags
          = stylesheet_link_tag "application", :media => "all"
          / For third-generation iPad with high-resolution Retina display:
          / Size should be 144 x 144 pixels
          = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
          / For iPhone with high-resolution Retina display:
          / Size should be 114 x 114 pixels
          = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
          / For first- and second-generation iPad:
          / Size should be 72 x 72 pixels
          = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
          / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
          / Size should be 57 x 57 pixels
          = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
          / For all other devices
          / Size should be 32 x 32 pixels
          = favicon_link_tag '/favicon.ico', :rel => 'shortcut icon'
          = javascript_include_tag "application"
          / Le HTML5 shim, for IE6-8 support of HTML elements
          /[if lt IE 9]
            <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  %body
    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .navbar-inner
        .container
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "/"} InvoToDo
          #bs-example-navbar-collapse-1.collapse.navbar-collapse  
            /
              <div class="navbar-collapse collapse navbar-responsive-collapse">
              <ul class="nav navbar-nav">
              <li><haml:loud> link_to &amp;quot;Link1&amp;quot;, &amp;quot;/path1&amp;quot;  </haml:loud></li>
              <li><haml:loud> link_to &amp;quot;Link2&amp;quot;, &amp;quot;/path2&amp;quot;  </haml:loud></li>
              <li><haml:loud> link_to &amp;quot;Link3&amp;quot;, &amp;quot;/path3&amp;quot;  </haml:loud></li>
              </ul>
              </div>
            = render "/shared/tab_nav_and_header"       
    .container
      .row
        .col-lg-9.panel_down
          = bootstrap_flash
          = yield
        /
          <div class="col-lg-3">
          <div class="well sidebar-nav">
          <h3>Sidebar</h3>
          <ul class="nav nav-list">
          <li class="nav-header">Sidebar</li>
          <li><haml:loud> link_to &amp;quot;Link1&amp;quot;, &amp;quot;/path1&amp;quot;  </haml:loud></li>
          <li><haml:loud> link_to &amp;quot;Link2&amp;quot;, &amp;quot;/path2&amp;quot;  </haml:loud></li>
          <li><haml:loud> link_to &amp;quot;Link3&amp;quot;, &amp;quot;/path3&amp;quot;  </haml:loud></li>
          </ul>
          </div>
          </div>
      / /row
    %footer
      .container
        %p.text-muted @copyright 2016 InvoToDo .
    / /container

app/views/projects/_form.html.haml
= form_for @project, :html => { :class => "form-horizontal project" } do |f|
  - if @project.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@project.errors.count, "error")
          prohibited this project from being saved:
      .panel-body
        %ul
          - @project.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.label :title, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
    / = f.error_span(:title)
  .form-group
    = f.label :description, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :description, :class => 'form-control'
    / = f.error_span(:description)
  .form-group
    = f.label :is_private, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.check_box :is_private, :class => 'form-control'
    / = f.error_span(:is_private)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn btn-default'

app/views/projects/edit.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/projects/index.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:is_private)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @projects.each do |project|
      %tr
        %td= link_to project.id, project_path(project)
        %td= project.title
        %td= project.description
        %td= project.is_private
        %td= l project.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")),edit_project_path(project), :class => 'btn btn-default btn-xs' 
          = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          = link_to t('.new', :default => t("helpers.links.new")), new_project_path, class: 'btn-primary'                            |

app/views/projects/new.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/projects/show.html.haml
- model_class = Project
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:title)
      \:
  %dd= @project.title
  %dt
    %strong
      = model_class.human_attribute_name(:description)
      \:
  %dd= @project.description
  %dt
    %strong
      = model_class.human_attribute_name(:is_private)
      \:
  %dd= @project.is_private
= link_to t('.back', :default => t("helpers.links.back")), projects_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(@project), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(@project), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/shared/_tab_nav_and_header.html.haml
%ul.nav.navbar-nav.navbar-right{class: user_signed_in? ? "signed-in-navbar" : ""}

  - if !current_user
    %li
      = link_to "Sign in",new_user_session_path
    %li
      = link_to "Sign up",new_user_registration_path
  -else
    %li.dropdown
      / %a.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
      /   = image_tag(current_user.image.thumb.url)#image_tag(current_user.image.url)
      /   = current_user.full_name
      / %ul.dropdown-menu
      /   %li
      /     = link_to "Edit Profile",edit_user_registration_path
      /   %li.divider{:role => "separator"}

      /   %li
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        %i.fa.fa-user.fa-fw
        %i.fa.fa-caret-down
      %ul.dropdown-menu.dropdown-user
        %li
          %a{:href => "#"}
            %i.fa.fa-user.fa-fw
            User Profile
        / %li
        /   %a{:href => "#"}
        /     %i.fa.fa-gear.fa-fw
        /     Settings
        %li.divider
        %li
          = link_to destroy_user_session_path,method: :delete do
            %i.fa.fa-sign-out.fa-fw
            Logout